#ifndef __JC_STDINC_H
#define __JC_STDINC_H
#include <vector>
#include <string>
#include <memory>
#include <functional>
#include <type_traits>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <memory.h>
#include <cstddef>
#include <unordered_map>
#include <algorithm>
#include <new>
#include <utility>
#include "jc_platform.h"
#endif
